### ISSUE TITLE
padded suit moves weird

### ISSUE THREAD

**Issue by ryzunmm** [DarnHyena/CackleheimCode#6]
When drop padded suit. It moves around or stay still in other place but can not pick it up

**Comment by ryzunmm** [comment]
![제목 없음](https://user-images.githubusercontent.com/73376515/146517184-1f9aec8a-5035-4d7a-bde8-afb452465238.png)
maybe inertia tensor is too high?

**Comment by DarnHyena** [comment]
Ah, I know what happened. I seem to have somehow lost or forgot the box collider on it. Will be fixed with the next update!
